const cases=[
{id:'sinus',category:'동성리듬',level:'basic',title:'정상 동성리듬',hr:72,question:'이 리듬의 가장 적절한 판독은 무엇입니까?',options:['정상 동성리듬','심방세동','심실빈맥','완전 방실차단'],answer:0,explanation:'규칙적인 R-R 간격, 각 QRS 앞의 일정한 P파, 정상 범위의 심박수를 확인합니다.',finding:'규칙적 리듬·P-QRS 1:1',action:'증상과 활력징후를 함께 확인하고 지속 관찰',wave:'sinus'},
{id:'ischemia',category:'허혈·심근경색',level:'advanced',title:'심근허혈 의심',hr:88,question:'흉통 환자의 이 파형에서 우선 주목해야 할 변화는?',options:['ST 분절 하강','델타파','톱니모양 F파','폭이 넓은 QRS만 존재'],answer:0,explanation:'협심증에서는 발작 중 수평형 또는 하향형 ST 하강과 T파 역전이 관찰될 수 있습니다. 증상·12유도 ECG·심근효소를 함께 평가해야 합니다.',finding:'허혈성 ST 분절 하강',action:'흉통 사정, 12유도 ECG, 활력징후 확인 및 즉시 보고',wave:'stdepression'},
{id:'stemi',category:'허혈·심근경색',level:'advanced',title:'급성 ST 상승 의심',hr:96,question:'연속된 유도에서 이와 같은 변화가 확인될 때 가장 우선적인 판단은?',options:['급성 심근손상 가능성','정상 변이로 단정','심방조동','1도 방실차단'],answer:0,explanation:'임상 증상과 함께 연속된 유도의 ST 상승은 급성 심근경색을 의심하게 합니다. 실제 판단은 정확한 12유도 기준과 임상 맥락이 필요합니다.',finding:'ST 분절 상승',action:'응급 대응체계 활성화, 12유도 ECG 및 처방에 따른 초기 처치',wave:'stelevation'},
{id:'af',category:'심방성 부정맥',level:'basic',title:'심방세동',hr:132,question:'불규칙한 R-R 간격과 뚜렷한 P파 부재를 보이는 리듬은?',options:['심방세동','동성빈맥','심실세동','Mobitz I'],answer:0,explanation:'심방세동은 뚜렷한 P파가 없고 기저선이 잔물결처럼 보이며 심실 반응이 불규칙하게 나타납니다.',finding:'불규칙-불규칙, P파 부재',action:'혈역학적 안정성·맥박 결손 확인, 색전 위험과 처방 확인',wave:'af'},
{id:'flutter',category:'심방성 부정맥',level:'advanced',title:'심방조동',hr:150,question:'기저선의 반복적인 톱니모양 파형은 무엇을 시사합니까?',options:['심방조동','심실세동','정상 동성리듬','동성정지'],answer:0,explanation:'심방조동은 규칙적인 F파가 톱니모양으로 반복되며 일정한 전도비를 보일 수 있습니다.',finding:'톱니모양 F파',action:'심실 반응과 혈역학적 안정성 확인',wave:'flutter'},
{id:'vt',category:'심실성 부정맥',level:'advanced',title:'심실빈맥',hr:182,question:'의식 저하와 저혈압이 동반된 이 넓은 QRS 빈맥에서 우선 확인할 것은?',options:['맥박 유무와 혈역학적 안정성','P파 모양만 확인','정상 리듬으로 기록','운동을 권장'],answer:0,explanation:'심실빈맥은 넓고 규칙적인 QRS 빈맥으로 보일 수 있습니다. 환자 상태와 맥박 유무에 따라 즉시 응급 알고리즘을 적용합니다.',finding:'규칙적인 넓은 QRS 빈맥',action:'맥박 확인, 응급 호출, 제세동기/동기화 심율동전환 준비',wave:'vt'},
{id:'vf',category:'심실성 부정맥',level:'advanced',title:'심실세동',hr:0,question:'맥박이 없고 조직화된 QRS가 전혀 없는 이 리듬의 처치는?',options:['즉시 CPR과 제세동','보행 격려','24시간 후 재검','경구 수분만 공급'],answer:0,explanation:'심실세동은 효과적인 심박출이 없는 치명적 리듬입니다. 고품질 CPR과 신속한 제세동이 핵심입니다.',finding:'무질서한 파형·조직화된 QRS 없음',action:'즉시 CPR, 제세동, 전문소생술 시행',wave:'vf'},
{id:'avblock',category:'전도장애',level:'advanced',title:'완전 방실차단',hr:38,question:'P파와 QRS가 서로 독립적으로 나타나는 소견은?',options:['3도 방실차단','정상 동성리듬','심방세동','심실조기수축'],answer:0,explanation:'완전 방실차단에서는 심방과 심실이 독립적으로 탈분극하여 P-P와 R-R은 각각 규칙적이지만 서로 연관되지 않습니다.',finding:'방실 해리',action:'저관류 증상 확인, 경피적 심박동 준비 및 즉시 보고',wave:'block'}
];
const $=s=>document.querySelector(s);let current=null,answered=false,deferredPrompt=null;let stats=JSON.parse(localStorage.getItem('ecgStats')||'{"correct":0,"total":0,"seen":[]}');
const categories=['전체',...new Set(cases.map(x=>x.category))];categories.forEach(c=>$('#category').insertAdjacentHTML('beforeend',`<option>${c}</option>`));
function pathFor(type){const base=160,pts=[];const add=(x,y)=>pts.push(`${x},${y}`);if(type==='vf'){for(let x=0;x<=1000;x+=8)add(x,base+Math.sin(x*.17)*55+Math.sin(x*.53)*26);return 'M'+pts.join(' L');}let x=0;const beats=type==='vt'?9:type==='block'?3:type==='af'?7:5;const gap=1000/beats;for(let b=0;b<beats;b++){const start=b*gap;let jitter=type==='af'?(b%2?22:-14):0;if(type==='flutter'){for(let k=0;k<5;k++){add(start+k*gap/5,base);add(start+k*gap/5+gap/10,base-18);add(start+k*gap/5+gap/5,base)}}if(type==='af'){for(let k=0;k<8;k++)add(start+k*gap/8,base+Math.sin((start+k)*.7)*8)}if(type==='block'){add(start,base);add(start+18,base-16);add(start+35,base);add(start+gap*.45,base);add(start+gap*.49,base-48);add(start+gap*.54,base+62);add(start+gap*.59,base-28);add(start+gap*.66,base)}else if(type==='vt'){add(start,base);add(start+gap*.15,base-85);add(start+gap*.38,base+75);add(start+gap*.72,base-35);add(start+gap,base)}else{add(start,base);if(type!=='af'&&type!=='flutter'){add(start+gap*.12,base-15);add(start+gap*.22,base)}add(start+gap*.36+jitter,base);add(start+gap*.4+jitter,base-70);add(start+gap*.45+jitter,base+85);add(start+gap*.5+jitter,base-25);let st=base;if(type==='stdepression')st=base+28;if(type==='stelevation')st=base-30;add(start+gap*.58+jitter,st);add(start+gap*.72+jitter,st);add(start+gap*.82+jitter,base-22);add(start+gap*.94+jitter,base)}}return 'M'+pts.join(' L')}
function filtered(){return cases.filter(c=>($('#category').value==='전체'||c.category===$('#category').value)&&($('#level').value==='all'||c.level===$('#level').value))}
function newQuestion(){const pool=filtered();current=pool[Math.floor(Math.random()*pool.length)]||cases[0];answered=false;$('#caseTag').textContent=current.category;$('#caseTitle').textContent=current.title;$('#heartRate').textContent=current.hr||'—';$('#question').textContent=current.question;$('#wavePath').setAttribute('d',pathFor(current.wave));$('#feedback').hidden=true;$('#explainBtn').hidden=true;$('#explanation').hidden=true;$('#options').innerHTML='';current.options.forEach((o,i)=>{const b=document.createElement('button');b.className='option';b.textContent=o;b.onclick=()=>answer(i,b);$('#options').appendChild(b)});}
function answer(i,button){if(answered)return;answered=true;stats.total++;const correct=i===current.answer;if(correct)stats.correct++;if(!stats.seen.includes(current.id))stats.seen.push(current.id);localStorage.setItem('ecgStats',JSON.stringify(stats));[...document.querySelectorAll('.option')].forEach((b,n)=>{b.disabled=true;if(n===current.answer)b.classList.add('correct')});if(!correct)button.classList.add('wrong');$('#feedback').hidden=false;$('#feedback').textContent=correct?'정답입니다. 핵심 판독 근거를 확인해 보세요.':'오답입니다. 정답과 판독 근거를 함께 확인하세요.';$('#explainBtn').hidden=false;renderStats()}
function renderStats(){ $('#score').textContent=`${stats.correct} / ${stats.total}`;const pct=Math.round(stats.seen.length/cases.length*100);$('#progressBar').style.width=pct+'%';$('#progressText').textContent=stats.total?`총 ${stats.total}문제 풀이 · 정답률 ${Math.round(stats.correct/stats.total*100)}% · 사례 ${stats.seen.length}/${cases.length}개 경험`:'아직 풀이 기록이 없습니다.'}
$('#nextBtn').onclick=newQuestion;$('#category').onchange=newQuestion;$('#level').onchange=newQuestion;$('#explainBtn').onclick=()=>{$('#explanationText').textContent=current.explanation;$('#keyFinding').textContent=current.finding;$('#nursingAction').textContent=current.action;$('#explanation').hidden=false;$('#explanation').scrollIntoView({behavior:'smooth',block:'center'})};$('#resetBtn').onclick=()=>{stats={correct:0,total:0,seen:[]};localStorage.removeItem('ecgStats');renderStats()};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));renderStats();newQuestion();